function saveIssue(){
	
	var subject=$("#subject").val();
	 var account=$("#account").val();
	if(subject=="" && account=="" ){
		$("#subjectalert").slideDown();
		$("#subjectalert").fadeOut(5000);
		return false;
	}

	
	var code= $('.feedcomMessage').code();
	// <p><br></p> is code generated by Summernote for empty content
    if (code == '' || code == "<p><br></p>"){
    	$("#summeralert").slideDown();
		$("#summeralert").fadeOut(5000);
		return false;
    }
    
   
    
    var issueId=$("#issueId").val();
    var hospitalId=$("#hospitalId").val();
    var redflag= $("#redflag").val();
    
	$.ajax({
		url : 'saveNewIssue',
		type : "POST",
		dataType:'text',
		data : {
			subject : "" + subject,
			code : "" + code,
			issueId : "" + issueId,
			hospitalId : "" + hospitalId,
			redflag : ""+ redflag,
			account : ""+ account
			
		},
		async:false,
		success:function(data) {
			$("#issueSubjectId").val(data);
			 document.getElementById("mySubmit").click();			
	},
		error : function(errorThrown) {
			console.log("Error: " + errorThrown);
		}
	});
}


function saveISsueCommunicate(){
	
	
	var code= $('.feedcomMessage').code();
	// <p><br></p> is code generated by Summernote for empty content
    if (code == '' || code == "<p><br></p>"){
    	$("#summeralert").slideDown();
		$("#summeralert").fadeOut(3000);
		return false;
    }
    
	
	
	var userName=$("#userName").val();
	var IssueSubId=$("#IssueSubId").val();
	var code= $('.feedcomMessage').code();
	var counter=$("#counter").val();
	
	/*var d = new Date();
	
	c = d.getDate();     // Get current date
    month       = d.getMonth() + 1; // current month
    year        = d.getFullYear();
	
    alert('welcome ramesh');
	hour = d.getHours();

    min  = d.getMinutes();
   
   sec  = d.getSeconds();
    
   //var Actualdate= year+"-"+month+"-"+c+" "+hour+":"+min+":"+sec;
   var Actualdate= c+"-"+month+"-"+year+" "+hour+":"+min+":"+sec;
*/
	var date = new Date();
	var c = date.getDate();  
	month       = date.getMonth() + 1; // current month
    year        = date.getFullYear();
    var hours = date.getHours() > 12 ? date.getHours() - 12 : date.getHours();
    var am_pm = date.getHours() >= 12 ? "PM" : "AM";
    hours = hours < 10 ? "0" + hours : hours;
    var minutes = date.getMinutes() < 10 ? "0" + date.getMinutes() : date.getMinutes();
    var seconds = date.getSeconds() < 10 ? "0" + date.getSeconds() : date.getSeconds();
 time = hours + ":" + minutes +  " " + am_pm;
   // var Actualdate= c+"-"+month+"-"+year+" "+hours + ":" + minutes + ":" + seconds + " " + am_pm;

    time=c+"/"+month+"/"+year+" "+time;
	
	
   try{
	var tds = "<tr>";
		tds += " <td >" +
		" <div class=''>"+
		"<div class='col-md-2 col-xs-2 avatar'> </div>"+
		"<div class='col-md-10 col-xs-10'>"+
		"<div class='messages msg_receive' style='background: background: rgba(189,227,156,0.34);"+
					"background: -moz-linear-gradient(left, rgba(189,227,156,0.34) 21%, rgba(189,227,156,0.34) 38%, rgba(189,227,156,0.53) 56%, rgba(234,246,223,1) 100%);"+
					"background: -webkit-gradient(left top, right top, color-stop(21%, rgba(189,227,156,0.34)), color-stop(38%, rgba(189,227,156,0.34)), color-stop(56%, rgba(189,227,156,0.53)), color-stop(100%, rgba(234,246,223,1)));"+
					"background: -webkit-linear-gradient(left, rgba(189,227,156,0.34) 21%, rgba(189,227,156,0.34) 38%, rgba(189,227,156,0.53) 56%, rgba(234,246,223,1) 100%);"+
					"background: -o-linear-gradient(left, rgba(189,227,156,0.34) 21%, rgba(189,227,156,0.34) 38%, rgba(189,227,156,0.53) 56%, rgba(234,246,223,1) 100%);"+
					"background: -ms-linear-gradient(left, rgba(189,227,156,0.34) 21%, rgba(189,227,156,0.34) 38%, rgba(189,227,156,0.53) 56%, rgba(234,246,223,1) 100%);"+
					"background: linear-gradient(to right, rgba(189,227,156,0.34) 21%, rgba(189,227,156,0.34) 38%, rgba(189,227,156,0.53) 56%, rgba(234,246,223,1) 100%);"+
					"filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#bde39c', endColorstr='#eaf6df', GradientType=1 );' >"+
					"<p >"+code+"</p>"+
					"<time style='color: Gray ;' datetime='2009-11-13T20:00'>"+userName  +"&nbsp;&nbsp;&nbsp;"+time+"</time>"+
					"</div>"+
					"</div>"+
					"</div> </td> </tr>";
		
   }catch(excp){
		console.log("Live Chat "+excp);
	}

	
	
	
	$("#tblData tbody").append(tds);
	
	var statusId=$("#statusId").val();
	
	$.ajax({
		url : 'saveIssueCommunicate',
		type : "POST",
		dataType:'text',
		data : {
			IssueSubId : "" + IssueSubId,
			code : "" + code,
			counter : "" +counter,
			statusId : ""+statusId
		},
		async:false,
		success:function(data) {
			$("#counter").val(data);
			// document.getElementById("mySubmit").click();			
			$(".feedcomMessage").code("");
		
		},
		error : function(errorThrown) {
			console.log("Error: " + errorThrown);
		}
	});
	
}



function liveChat(){
	
	//    console.log(i);
   setInterval(function(){
	   	var IssueSubId=$("#IssueSubId").val();
		var counter=$("#counter").val();
				$.ajax({
			      	type : "POST",
			          url: "livechat",
			          data : "IssueSubId=" + IssueSubId +"&counter="+counter,
			          cache: false,
			          dataType: "json",
			          success: function(data) {
			        	  if(data==""){
			        		//  alert("empty");
			        		  console.log("empty");
			        	  }
			        	  else{
				        		//  alert(data);
					        	  console.log(data);
					      		 for (i=0; i < data.length; i++) 
					      		 { 
					      			var date = new Date();
					      			var c = date.getDate();  
					      			month       = date.getMonth() + 1; // current month
					      		    year        = date.getFullYear();
					      		    var hours = date.getHours() > 12 ? date.getHours() - 12 : date.getHours();
					      		    var am_pm = date.getHours() >= 12 ? "PM" : "AM";
					      		    hours = hours < 10 ? "0" + hours : hours;
					      		    var minutes = date.getMinutes() < 10 ? "0" + date.getMinutes() : date.getMinutes();
					      		    var seconds = date.getSeconds() < 10 ? "0" + date.getSeconds() : date.getSeconds();
					      		 time = hours + ":" + minutes +  " " + am_pm;
					      		   // var Actualdate= c+"-"+month+"-"+year+" "+hours + ":" + minutes + ":" + seconds + " " + am_pm;

					      		    time=c+"/"+month+"/"+year+" "+time;
					          		
					          		var tds = "<tr>";
					          		tds += " <td >" +
					          		" <div class=''>"+
						                        "<div class='col-md-10 col-xs-10'>"+
						                        "<div class='messages msg_sent' style='background: background: rgba(149,215,233,0.34);"+
									"background: -moz-linear-gradient(left, rgba(149,215,233,0.34) 21%, rgba(149,215,233,0.34) 38%, rgba(149,215,233,0.53) 56%, rgba(221,243,249,1) 100%);"+
									"background: -webkit-gradient(left top, right top, color-stop(21%, rgba(149,215,233,0.34)), color-stop(38%, rgba(149,215,233,0.34)), color-stop(56%, rgba(149,215,233,0.53)), color-stop(100%, rgba(221,243,249,1)));"+
									"background: -webkit-linear-gradient(left, rgba(149,215,233,0.34) 21%, rgba(149,215,233,0.34) 38%, rgba(149,215,233,0.53) 56%, rgba(221,243,249,1) 100%);"+
									"background: -o-linear-gradient(left, rgba(149,215,233,0.34) 21%, rgba(149,215,233,0.34) 38%, rgba(149,215,233,0.53) 56%, rgba(221,243,249,1) 100%);"+
									"background: -ms-linear-gradient(left, rgba(149,215,233,0.34) 21%, rgba(149,215,233,0.34) 38%, rgba(149,215,233,0.53) 56%, rgba(221,243,249,1) 100%);"+
									"background: linear-gradient(to right, rgba(149,215,233,0.34) 21%, rgba(149,215,233,0.34) 38%, rgba(149,215,233,0.53) 56%, rgba(221,243,249,1) 100%);"+
				                    "filter: progid:DXImageTransform.Microsoft.gradient( startColorstr='#95d7e9', endColorstr='#ddf3f9', GradientType=1 );' >"+
				                    "<p >"+data[i].issueDetail+"</p>"+
				                    "<time style='color: Gray ;' datetime='2009-11-13T20:00'>"+data[i].userModelFrom.userName  +"&nbsp;&nbsp;&nbsp;"+time+"</time>"+
				                    "</div>"+
				                    "</div>"+
				                    "<div class='col-md-2 col-xs-2 '>" +
				                    "</div>" +
				                    "</div>"+				                            
				                    "</div> </td> </tr>";
					          		$("#tblData tbody").append(tds);
					          		$("#counter").val(data[i].issueDetailId);
					          	}
					      		
			        	  }
			          },
			          error : function(xhr, ajaxOptions, thrownError) {
			        	  console.log("Error In Live Chat" + thrownError + xhr.responseText);
			  	//		alert("err" + thrownError + xhr.responseText);
			  		}
				});
}, 1000);
}



